# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75800e5e244afed3c6b8815dcba79e851cd97a3653d511d991b5ca5a3051f75cd68417e758d423fba80ce8a3ff2cb2ffa46830244584c0aec2083505fdfac5be

test:
  secret_key_base: 02f6a3364fad0b385d18e525e4db656bc06adf9d96c89b3acdb3ad4b2ff697486533f5f6e9884df103f1fff5a66ab24bbcd3d2599cdbca9a4e7e9b458af66f29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
